title: Hactoberfest 2021

url: "https://abhishek-g0yal.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "/Hacktoberfest-2021" # the subpath of your site, e.g. /blog

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty
